# Generated by Django 2.2.16 on 2022-05-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220512_1105'),
        ('users', '0002_auto_20220512_1356'),
    ]

    operations = [
    ]
