# Generated by Django 2.2.16 on 2022-05-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20220512_1710'),
        ('users', '0004_merge_20220512_1912'),
    ]

    operations = [
    ]
