# Generated by Django 2.2.16 on 2022-05-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20220513_1134'),
        ('users', '0005_merge_20220512_2213'),
    ]

    operations = [
    ]
