# Generated by Django 2.2.16 on 2022-05-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220511_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='category',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='description',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='name',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='year',
        ),
    ]
