# Generated by Django 2.2.16 on 2022-05-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220511_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.Category'),
        ),
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.Genre'),
        ),
        migrations.AddField(
            model_name='titles',
            name='name',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='titles',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
