# Generated by Django 2.2.16 on 2022-05-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220511_1913'),
        ('reviews', '0003_auto_20220511_2150'),
    ]

    operations = [
    ]
