# Generated by Django 2.2.16 on 2022-05-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_merge_20220511_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='123', max_length=256),
        ),
    ]
