# Generated by Django 2.2.16 on 2022-05-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
    ]
