# Generated by Django 2.2.16 on 2022-05-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20220512_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title_id'), name='unique_author_review'),
        ),
    ]
