# Generated by Django 2.2.16 on 2022-05-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0037_auto_20220514_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('slug',)},
        ),
    ]
