# Generated by Django 2.2.16 on 2022-05-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0038_auto_20220514_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
