# Generated by Django 2.2.16 on 2022-05-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0042_auto_20220515_0833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
    ]
