# Generated by Django 2.2.16 on 2022-05-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0043_auto_20220515_0951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
